In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr=np.array([0,1,2,3,4,5])
print(arr[2:])

[2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[:3])

[1 2 3]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0:2,1:3])

[[2 3]
 [6 7]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4])

10


In [ ]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]
3
(1, 4, 5)


In [ ]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr[0,1,2])


8


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
arr=np.array(["apple","banana","mango"])
print(arr.dtype)

<U6


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
import numpy as np
arr=([1,2,3,4,5])
x = arr.copy()
arr[0]= 55

print(arr)
print(x)

[55, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x= arr.view()
arr[0]=33
print(x)
print(arr)

[33  2  3  4  5]
[33  2  3  4  5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr.ndim)

2


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
  print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [53]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in arr:
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [56]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
arr=arr1+arr2
arrr=np.concatenate((arr1,arr2))
print(arr)
print(arrr)

[ 2  4  6  8 10]
[1 2 3 4 5 1 2 3 4 5]


In [58]:
arr=np.array([1,2222323221232324,53453455534534543534,5345345345345345345345,5435345345345345345,53454534534534543534534,423422233243243345,53453442343232423423,42332434233423423423,432423324234234])
arrr=np.array([1,2,3,4,5,6,7,8,9,1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000])
arrrr=np.concatenate((arr,arrr))
print(arrrr)

[1 2222323221232324 53453455534534543534 5345345345345345345345
 5435345345345345345 53454534534534543534534 423422233243243345
 53453442343232423423 42332434233423423423 432423324234234 1 2 3 4 5 6 7 8
 9
 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


In [61]:
import numpy as np
ar=np.array([[1,2],[3,4]])
arr=np.array([[5,6],[7,8]])
arrr=np.concatenate((ar,arr),axis=1)
print(arrr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
a=np.array